
  [90m[32mâœ”[39m[90m foo[39m

  [31m1) integration-tests/fixture-tests/asynchronous-activity-test/test.ts[39m [31m[3m(202ms)[23m[39m


[32m1 passing[39m[90m (228ms)[39m[31m[39m
[31m1 failing[39m
[34mâ„¹[39m Error: Test "foo" at integration-tests/fixture-tests/asynchronous-activity-test/test.ts:1:29 generated asynchronous activity after the test ended. This activity created the error "Error" and would have caused the test to fail, but instead triggered an uncaughtException event.

  1) integration-tests/fixture-tests/asynchronous-activity-test/test.ts:

   [31mTest file execution failed (exit code 1).[39m

